# Generated by Django 3.0.7 on 2020-08-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imageMovie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
