# Generated by Django 3.0.7 on 2020-08-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200810_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='reviewMovie',
            field=models.TextField(null=True),
        ),
    ]
