# Generated by Django 3.0.7 on 2020-08-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_movies_reviewmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='typeMovie',
            field=models.ManyToManyField(to='Home.TypeMovies'),
        ),
    ]
