# Generated by Django 3.0.7 on 2020-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200814_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorstable',
            name='Actor',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='Director',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='typemovies',
            name='Type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
