# Generated by Django 3.0.7 on 2020-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200814_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imageMovie',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieTitle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
